imports:
    - { resource: config_dev.yml }

liip_functional_test:
  cache_sqlite_db: true

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db"
            bio_control:
              driver:   sqlsrv
              host:     "%bio_control_host%"
              dbname:   "%bio_control_name%"
              user:     "%bio_control_user%"
              password: "%bio_control_password%"