# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER
        ROLE_MANAGER: ROLE_ADMIN
        ROLE_DIRECTOR: ROLE_MANAGER

    providers:
      chain_provider:
         chain:
            providers: [fos_userbundle, fr3d_ldapbundle]
      fr3d_ldapbundle:
         id: fr3d_ldap.security.user.provider
      fos_userbundle:
         id: fos_user.user_provider.username

    firewalls:
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
        main:
           pattern: ^/
           fr3d_ldap:  ~
           form_login:
             always_use_default_target_path: true
             default_target_path: /
             csrf_token_generator: security.csrf.token_manager
           logout:       true
           anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }