# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.file_uploader:
          class: AppBundle\Uploader\FileUploader
          arguments: ['%file_directory%']
  app.doctrine_entity_listener:
          class: AppBundle\EventListener\EntityListener
          arguments: ['@app.file_uploader', '@logger']
          tags:
              - { name: doctrine.event_listener, event: prePersist }
              - { name: doctrine.event_listener, event: preUpdate }
              - { name: doctrine.event_listener, event: preRemove }
